import React from 'react'

const PackingInstructionsModal = ({ data, onClose }) => {
  if (!data) return null

  const { loading, shipment, instructions, error } = data

  return (
    <div className="modal">
      <div className="modal-content" style={{ maxWidth: '600px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
          <h3>🤖 AI Packing Instructions</h3>
          <button 
            onClick={onClose}
            style={{ 
              background: 'none', 
              border: 'none', 
              fontSize: '24px', 
              cursor: 'pointer',
              color: '#666'
            }}
          >
            ×
          </button>
        </div>

        {shipment && (
          <div style={{
            background: '#f8f9fa',
            padding: '1rem',
            borderRadius: '4px',
            marginBottom: '1.5rem'
          }}>
            <h4 style={{ margin: '0 0 0.5rem 0' }}>Shipment Details</h4>
            <p style={{ margin: 0, fontSize: '14px' }}>
              <strong>Item:</strong> {shipment.description}<br />
              <strong>Type:</strong> {shipment.is_fragile ? 'Fragile' : 'Standard'}<br />
              <strong>Method:</strong> {shipment.shipping_method}<br />
              <strong>Route:</strong> {shipment.origin} → {shipment.destination}
            </p>
          </div>
        )}

        {loading && (
          <div style={{ 
            textAlign: 'center', 
            padding: '3rem',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: '1rem'
          }}>
            <div style={{
              width: '40px',
              height: '40px',
              border: '4px solid #f3f3f3',
              borderTop: '4px solid #007bff',
              borderRadius: '50%',
              animation: 'spin 1s linear infinite'
            }}></div>
            <div>Generating AI packing instructions...</div>
            <style jsx>{`
              @keyframes spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
              }
            `}</style>
          </div>
        )}

        {error && (
          <div style={{
            color: '#dc3545',
            background: '#f8d7da',
            border: '1px solid #f5c6cb',
            padding: '1rem',
            borderRadius: '4px',
            marginBottom: '1rem'
          }}>
            <strong>Error:</strong> {error}
          </div>
        )}

        {instructions && (
          <div>
            <div style={{
              background: '#e7f3ff',
              border: '1px solid #b3d9ff',
              borderRadius: '4px',
              padding: '1rem',
              marginBottom: '1.5rem'
            }}>
              <div style={{
                color: '#004085',
                fontSize: '14px',
                fontWeight: 'bold',
                marginBottom: '0.5rem'
              }}>
                ✨ AI-Generated Packing Instructions
              </div>
              <div style={{
                whiteSpace: 'pre-wrap',
                lineHeight: '1.6',
                color: '#333'
              }}>
                {instructions}
              </div>
            </div>
            
            <div style={{
              fontSize: '12px',
              color: '#666',
              fontStyle: 'italic',
              textAlign: 'center',
              marginBottom: '1rem'
            }}>
              These instructions were generated by AI based on your shipment details. 
              Please review and adapt them according to your specific needs.
            </div>
          </div>
        )}

        <div style={{ textAlign: 'center' }}>
          <button onClick={onClose} className="btn btn-primary">
            Close
          </button>
        </div>
      </div>
    </div>
  )
}

export default PackingInstructionsModal
